// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/toastsandwich/ewaste-collection-caller/views/base"

func home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-center bg-light p-5 rounded\"><h1 class=\"mb-4 text-success\">Welcome to the E-Waste Drive Scheduler</h1><p class=\"lead text-muted\">Help the environment by properly disposing of your e-waste.</p><div class=\"mb-4\"><a href=\"/drives\" class=\"btn btn-primary btn-lg m-2\">View Upcoming Drives</a> <a href=\"/schedule-drive\" class=\"btn btn-primary btn-lg m-2\">Schedule a Drive</a></div><div class=\"mt-4\"><h5 class=\"text-info\">Awareness on E-Waste Management</h5><p class=\"text-justify\">E-waste is a growing environmental concern. Proper disposal helps prevent harmful effects on the environment and human health.  We encourage you to stay informed and be proactive in managing your e-waste.</p><p class=\"text-justify\">Feel free to schedule drives through our website. Stay active, check the schedule, and join possible drives!</p></div></div><div class=\"mt-5\"><h2 class=\"text-center text-success\">Join the Movement!</h2><p class=\"text-center\"><img src=\"assets/plug.png\" alt=\"Recycling Symbol\" class=\"img-fluid\" style=\"max-width: 300px;\"></p><p class=\"text-center\">\"Together, we can make a difference! Every small effort counts towards a cleaner planet.\"</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = base.Base("Home", home()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
